language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"

matrix:
  include:
    - php: 7.3
      env: PREFER_LOWEST=""
    - php: 7.4snapshot
      env: PREFER_LOWEST=""

allow_failures:
  - php: '7.4snapshot'


services:
  - mysql

cache:
  directories:
    - vendor

before_install:
  - export MYSQL_DATABASE=test
  - export MYSQL_USER=my_app
  - export MYSQL_PASSWORD=secret
  - export DB_HOST=localhost

before_script:
  - mysql -u root < tests/test_app/database/init/001_init_database.sql
  - mysql -u root -e "CREATE USER 'my_app'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';"
  - mysql -u root -e "CREATE USER 'second_user'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}${MYSQL_PASSWORD}';"
  - mysql -u root -e "CREATE USER 'third_user'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}${MYSQL_PASSWORD}${MYSQL_PASSWORD}';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'my_app';"
  - mysql -u root -e "GRANT SELECT,SUPER ON *.* TO 'second_user';"
  - mysql -u root -e "GRANT SELECT,SUPER ON *.* TO 'third_user';"
  - composer update --prefer-dist --no-interaction $PREFER_LOWEST

script:
  - |
      if [[ $TRAVIS_PHP_VERSION == '7.3' ]]; then
        vendor/bin/phpunit --verbose --coverage-clover=clover.xml
        composer stan-setup
        composer stan
      else
        composer test
      fi

after_success:
  - |
      # obrained from https://github.com/codecov/codecov-bash/issues/133#issuecomment-447337868
      if [[ $TRAVIS_PHP_VERSION == '7.3' ]]; then
        curl -s https://codecov.io/bash > codecov
        sed -i -e 's/TRAVIS_.*_VERSION/^TRAVIS_.*_VERSION=/' codecov
        bash codecov
      fi